### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by elhertz** [MKSx/EnviarAudio-BetterDiscord#1]
Hey, i love your plugin and I don't know if you'll keep updating it. I hope you do :D

**Comment by MKSx** [comment]
Hello, sorry for the delay in answering you

The plugin stopped working due to the change in Metalloriff lib, but that was fixed and also a small problem that was giving time to record the audio.

I will try to keep the plugin updated and go by fixing the bugs and improving it.

I didn't know anyone was using this plugin as I just jokingly tried to learn more about javascript, but I'm glad to hear that.

Of course please give suggestions or report other problems I am grateful.

And sorry for my english, i ended up using google translator

**Comment by elhertz** [comment]
Thank you so much!
I love this plugin and i'll try to keep in contact with you for new suggestions.
